-- Optional: scheduling via pg_cron + pg_net (run in Supabase SQL editor)
-- Ensure extensions enabled in Supabase dashboard.
-- Note: ingest-bars, validate-bars, and generate-signals use CRON_SECRET (x-cron-secret header) and verify_jwt=false.
-- select cron.schedule('ingest-h1', '2 * * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/ingest-bars',
--     headers:='{"Content-Type":"application/json","x-cron-secret":"<cron-secret>"}');
-- $$);
-- select cron.schedule('validate-h1', '3 * * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/validate-bars',
--     headers:='{"Content-Type":"application/json","x-cron-secret":"<cron-secret>"}');
-- $$);
-- select cron.schedule('signals-h1', '4 * * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/generate-signals',
--     headers:='{"Content-Type":"application/json","x-cron-secret":"<cron-secret>"}');
-- $$);
-- select cron.schedule('ingest-history-nightly', '15 0 * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/ingest-history',
--     headers:='{"Content-Type":"application/json","x-cron-secret":"<cron-secret>"}');
-- $$);
-- select cron.schedule('fill-missing-bars-hourly', '20 * * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/fill-missing-bars',
--     headers:='{"Content-Type":"application/json","x-cron-secret":"<cron-secret>"}');
-- $$);
-- select cron.schedule('notify', '* * * * *', $$
--   select net.http_post(url:='https://<project-ref>.functions.supabase.co/notify',
--     headers:='{"Content-Type":"application/json","Authorization":"Bearer <service-role>"}');
-- $$);
